---
- hosts: all
  vars:
    passw: <-DIGESTED-PASS->
    username: javier.contreras
  become: true
  tasks:
  - name: "Insert user"
    user: name={{username}} shell=/bin/bash groups=sudo append=yes password={{passw}}

  - name: "Create .ssh folder"
    file: path=/home/{{username}}/.ssh state=directory mode=700
    become_user: "{{username}}"

  - name: "Insert public key into guest"
    copy: src=support/id_rsa.pub dest=/home/{{username}}/.ssh/authorized_keys mode=600
    become_user: "{{username}}"

  - name: "Provide private key to the guest"
    copy: src=support/id_rsa dest=/home/{{username}}/.ssh/id_rsa mode=600
    become_user: "{{username}}"

  - name: "Tmux setup: add apt repo"
    apt_repository: repo='ppa:pi-rho/dev'

  - name:  "Install linux packages"
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - git
      - tig
      - python-software-properties
      - software-properties-common
      - tmux
      - rbenv

  - name: "Include github.com in ssh known hosts"
    shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts

  - name: "Clone dotfile"
    git: repo=git://github.com/thebigw4lrus/dotfiles.git dest=~/dotfiles
    become_user: "{{username}}"

  - name: "Install Vundle"
    git: repo=git://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
    become_user: "{{username}}"

  - name: "Install dotfiles"
    shell: make -C ~/dotfiles install
    become_user: "{{username}}"
